//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import <Flutter/Flutter.h>
#import <AMapLocationKit/AMapLocationKit.h>

@interface AmapLocationFluttifyPlugin : NSObject<AMapGeoFenceManagerDelegate, AMapLocationManagerDelegate, FlutterPlugin>

- (instancetype) initWithFlutterPluginRegistrar: (NSObject <FlutterPluginRegistrar> *) registrar;

@end
