// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

mixin com_amap_api_location_LocationManagerBase on java_lang_Object {
  

  

  

  @mustCallSuper
  Future<void> setLocationOption(com_amap_api_location_AMapLocationClientOption var1) {
    kNativeObjectPool.add(var1);
  
    if (fluttifyLogEnabled) {
      debugPrint('setLocationOption::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> setLocationListener(com_amap_api_location_AMapLocationListener var1) {
    kNativeObjectPool.add(var1);
  
    if (fluttifyLogEnabled) {
      debugPrint('setLocationListener::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> startLocation() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('startLocation::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> stopLocation() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('stopLocation::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<com_amap_api_location_AMapLocation> getLastKnownLocation() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getLastKnownLocation::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> startAssistantLocation() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('startAssistantLocation::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> stopAssistantLocation() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('stopAssistantLocation::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> isStarted() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('isStarted::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> unRegisterLocationListener(com_amap_api_location_AMapLocationListener var1) {
    kNativeObjectPool.add(var1);
  
    if (fluttifyLogEnabled) {
      debugPrint('unRegisterLocationListener::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onDestroy() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onDestroy::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> disableBackgroundLocation(bool var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('disableBackgroundLocation::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}