// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapGeoFenceActiveAction {
  AMapGeoFenceActiveActionNone /* 0 */,
  AMapGeoFenceActiveActionInside /* null */,
  AMapGeoFenceActiveActionOutside /* null */,
  AMapGeoFenceActiveActionStayed /* null */
}

extension AMapGeoFenceActiveActionToX on AMapGeoFenceActiveAction {
  int toValue() {
    switch (this) {
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionNone: return 0;
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionInside: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionInside.index + 0;
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionOutside: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionOutside.index + 0;
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionStayed: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionStayed.index + 0;
    }
  }
}

extension AMapGeoFenceActiveActionFromX on int {
  AMapGeoFenceActiveAction toAMapGeoFenceActiveAction() {
    switch (this) {
      case 0: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionNone;
      default: return AMapGeoFenceActiveAction.values[this + 0];
    }
  }
}