// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapGeoFenceActiveAction {
  AMapGeoFenceActiveActionNone /* 0 */,
  AMapGeoFenceActiveActionInside /* 1<<0 */,
  AMapGeoFenceActiveActionOutside /* 1<<1 */,
  AMapGeoFenceActiveActionStayed /* 1<<2 */
}

extension AMapGeoFenceActiveActionToX on AMapGeoFenceActiveAction {
  int toValue() {
    switch (this) {
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionNone: return 0;
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionInside: return 1<<0;
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionOutside: return 1<<1;
      case AMapGeoFenceActiveAction.AMapGeoFenceActiveActionStayed: return 1<<2;
      default: return 0;
    }
  }
}

extension AMapGeoFenceActiveActionFromX on int {
  AMapGeoFenceActiveAction toAMapGeoFenceActiveAction() {
    switch (this) {
      case 0: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionNone;
      case 1<<0: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionInside;
      case 1<<1: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionOutside;
      case 1<<2: return AMapGeoFenceActiveAction.AMapGeoFenceActiveActionStayed;
      default: return AMapGeoFenceActiveAction.values[this + 0];
    }
  }
}