// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';



mixin AMapLocationManagerDelegate on NSObject {
  

  

  

  

  @mustCallSuper
  Future<void> amapLocationManager_doRequireLocationAuth(AMapLocationManager manager, CLLocationManager locationManager) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(locationManager);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_doRequireLocationAuth::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didFailWithError(AMapLocationManager manager, NSError error) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(error);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didFailWithError::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didUpdateLocation(AMapLocationManager manager, CLLocation location) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(location);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didUpdateLocation::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didUpdateLocation_reGeocode(AMapLocationManager manager, CLLocation location, AMapLocationReGeocode reGeocode) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(location);
    kNativeObjectPool.add(reGeocode);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didUpdateLocation_reGeocode::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didChangeAuthorizationStatus(AMapLocationManager manager, CLAuthorizationStatus status) {
    kNativeObjectPool.add(manager);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didChangeAuthorizationStatus::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> amapLocationManagerShouldDisplayHeadingCalibration(AMapLocationManager manager) {
    kNativeObjectPool.add(manager);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManagerShouldDisplayHeadingCalibration::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didUpdateHeading(AMapLocationManager manager, CLHeading newHeading) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(newHeading);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didUpdateHeading::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didStartMonitoringForRegion(AMapLocationManager manager, AMapLocationRegion region) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(region);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didStartMonitoringForRegion::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didEnterRegion(AMapLocationManager manager, AMapLocationRegion region) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(region);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didEnterRegion::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didExitRegion(AMapLocationManager manager, AMapLocationRegion region) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(region);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didExitRegion::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_didDetermineState_forRegion(AMapLocationManager manager, AMapLocationRegionState state, AMapLocationRegion region) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(region);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_didDetermineState_forRegion::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> amapLocationManager_monitoringDidFailForRegion_withError(AMapLocationManager manager, AMapLocationRegion region, NSError error) {
    kNativeObjectPool.add(manager);
    kNativeObjectPool.add(region);
    kNativeObjectPool.add(error);
  
    if (fluttifyLogEnabled) {
      debugPrint('amapLocationManager_monitoringDidFailForRegion_withError::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}

