// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapGeoFenceErrorCode {
  AMapGeoFenceErrorUnknown /* 1 */,
  AMapGeoFenceErrorInvalidParameter /* 2 */,
  AMapGeoFenceErrorFailureConnection /* 3 */,
  AMapGeoFenceErrorFailureAuth /* 4 */,
  AMapGeoFenceErrorNoValidFence /* 5 */,
  AMapGeoFenceErroFailureLocating /* 6 */
}