// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapLocationCoordinateType {
  AMapLocationCoordinateTypeBaidu /* 0 */,
  AMapLocationCoordinateTypeMapBar /* 0 */,
  AMapLocationCoordinateTypeMapABC /* 0 */,
  AMapLocationCoordinateTypeSoSoMap /* 0 */,
  AMapLocationCoordinateTypeAliYun /* 0 */,
  AMapLocationCoordinateTypeGoogle /* 0 */,
  AMapLocationCoordinateTypeGPS /* 0 */
}